import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./query-provider";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <QueryProvider>
          <TooltipProvider>
            <Toaster />
            <Navbar />
            <main>{children}</main>
          </TooltipProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
